export const ADD_CITY_TO_FAVOURITES = 'ADD_CITY_TO_FAVOURITES'
export const REMOVE_CITY_FROM_FAVORITES = 'REMOVE_CITY_FROM_FAVORITES'

export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'

export const SWITCH_MODE = 'SWITCH_MODE'
export const SWITCH_TEMPERATURE_UNIT = 'SWITCH_TEMPERATURE_UNIT'

export const STORE_SEARCH_RESULT = 'STORE_SEARCH_RESULT'
export const FORECAST_SEARCH_RESULT = 'FORECAST_SEARCH_RESULT'

export const DEFINE_FIRST_LAUNCH = 'DEFINE_FIRST_LAUNCH'

export const SET_SEARCH_REQUEST = 'SET_SEARCH_REQUEST'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const CLOSE_NOTIFICATION = 'CLEAR_NOTIFICATION'

export const SHOW_TEXTFIELD_ERROR = 'SHOW_TEXTFIELD_ERROR'
